services:
  - type: web
    name: todo-app
    runtime: dotnet
    repo: https://github.com/Sibu912/TodoApp
    plan: free
    rootDir: TodoBlazor
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/TodoBlazor.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
