services:
  - type: web
    name: todo-app
    runtime: docker
    repo: https://github.com/Sibu912/TodoApp
    plan: free
    rootDir: ToDoList
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
